# Generated by Django 4.2.14 on 2024-09-17 05:05

import cloudinary.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', cloudinary.models.CloudinaryField(max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('rom_quality', models.CharField(max_length=255)),
                ('hotel_desc', models.TextField()),
                ('hotel_address', models.CharField(max_length=255)),
                ('hotel_phone', models.CharField(max_length=255)),
                ('hotel_email', models.EmailField(max_length=255)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelRom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('bed_quality', models.CharField(max_length=255)),
                ('price_adult', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_child', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_pet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.CharField(max_length=255)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, null=True)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookingapp.hotel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('start_date', models.CharField(max_length=255)),
                ('end_date', models.CharField(max_length=255)),
                ('discount_percentage', models.CharField(max_length=255)),
                ('discount_amount', models.CharField(max_length=255)),
                ('min_booking_amount', models.CharField(max_length=255)),
                ('max_uses', models.CharField(default=1, max_length=255)),
                ('current_uses', models.CharField(default=0, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('discount_percentage', models.CharField(max_length=255)),
                ('discount_amount', models.CharField(max_length=255)),
                ('start_date', models.CharField(max_length=255)),
                ('end_date', models.CharField(max_length=255)),
                ('min_booking_amount', models.CharField(max_length=255)),
                ('max_uses', models.CharField(default=1, max_length=255)),
                ('current_uses', models.CharField(default=0, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoucherRom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.hotelrom')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherPromotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.promotions')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.voucher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RomImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, null=True)),
                ('hotelroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.hotelrom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HotelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('service', models.CharField(default='Không có', max_length=255)),
                ('activity', models.CharField(default='Không có', max_length=255)),
                ('cuisine', models.CharField(default='Không có', max_length=255)),
                ('room_amenity', models.CharField(default='Không có', max_length=255)),
                ('office_amenity', models.CharField(default='Không có', max_length=255)),
                ('nearby_amenity', models.CharField(default='Không có', max_length=255)),
                ('family_friendly_amenity', models.CharField(default='Không có', max_length=255)),
                ('transportation_amenity', models.CharField(default='Không có', max_length=255)),
                ('disability_support_amenity', models.CharField(default='Không có', max_length=255)),
                ('child_friendly_amenity', models.CharField(default='Không có', max_length=255)),
                ('pet_friendly_amenity', models.CharField(default='Không có', max_length=255)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.hotel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hotelrom',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.typeroom'),
        ),
        migrations.AddField(
            model_name='hotelrom',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HotelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('rom_quality', models.CharField(max_length=255)),
                ('hotel_desc', models.TextField()),
                ('hotel_address', models.CharField(max_length=255)),
                ('hotel_phone', models.CharField(max_length=255)),
                ('hotel_email', models.EmailField(max_length=255)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HotelImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, null=True)),
                ('hotel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bookingapp.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.province'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('birthday', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=255)),
                ('cccd', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('avatar', cloudinary.models.CloudinaryField(max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('birthday', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=255)),
                ('cccd', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('avatar', cloudinary.models.CloudinaryField(max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('content', models.CharField(max_length=255)),
                ('cleanliness_rating', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('comfort_rating', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('food_rating', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('location_rating', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('service_rating', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('hotelroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.hotelrom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('check_in_date', models.CharField(max_length=255)),
                ('check_out_date', models.CharField(max_length=255)),
                ('total_amount', models.CharField(max_length=255)),
                ('payment_method', models.CharField(default='Trực tiếp', max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.customer')),
                ('hotel_rom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.hotelrom')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.voucher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_price', models.CharField(max_length=255)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.bookings')),
                ('rom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.hotelrom')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bookingapp.role'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
