# Generated by Django 4.2.14 on 2024-09-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_alter_hotelimages_hotel_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelimages',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
