# Generated by Django 4.2.14 on 2024-09-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0005_remove_hotelimages_hotel_request_hotelimages_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelrequest',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
