# Generated by Django 4.2.14 on 2024-09-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0006_remove_hotelimages_hotel_request_hotelrequest_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelrequest',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
