# Generated by Django 4.2.14 on 2024-09-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0008_remove_hotelimages_hotel_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelrequest',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelrequest',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
