# Generated by Django 4.2.14 on 2024-09-17 10:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0009_remove_hotelimages_hotel_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimages',
            name='hotelrequest',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookingapp.hotelrequest'),
        ),
        migrations.AlterField(
            model_name='hotelrequest',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hotelrequest',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
