# Generated by Django 4.2.14 on 2024-09-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0010_remove_hotelimages_hotel_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bookings',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotelrom',
            name='additional_child_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hotelrom',
            name='additional_pet_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hotelrom',
            name='applies_additional_child_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelrom',
            name='applies_additional_pet_fee',
            field=models.BooleanField(default=False),
        ),
    ]
