# Generated by Django 4.2.14 on 2024-09-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0011_remove_hotelimages_hotel_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelservice',
            name='activity',
            field=models.TextField(default='Không có', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelservice',
            name='child_friendly_amenity',
            field=models.TextField(default='Không có', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelservice',
            name='cuisine',
            field=models.TextField(default='Không có', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelservice',
            name='disability_support_amenity',
            field=models.TextField(default='Không có', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelservice',
            name='family_friendly_amenity',
            field=models.TextField(default='Không có', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelservice',
            name='nearby_amenity',
            field=models.TextField(default='Không có', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelservice',
            name='office_amenity',
            field=models.TextField(default='Không có', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelservice',
            name='pet_friendly_amenity',
            field=models.TextField(default='Không có', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelservice',
            name='room_amenity',
            field=models.TextField(default='Không có', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelservice',
            name='service',
            field=models.TextField(default='Không có', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelservice',
            name='transportation_amenity',
            field=models.TextField(default='Không có', max_length=255),
        ),
    ]
