# Generated by Django 4.2.14 on 2024-09-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0012_remove_hotelimages_hotel_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelrom',
            name='available_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
