# Generated by Django 4.2.14 on 2024-09-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0013_remove_hotelimages_hotel_request_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='romimages',
            old_name='hotelroom',
            new_name='hotel_room',
        ),
    ]
