# Generated by Django 4.2.14 on 2024-09-29 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0014_rename_hotelroom_romimages_hotel_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherrom',
            name='hotel_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.hotel'),
        ),
    ]
