# Generated by Django 4.2.14 on 2024-09-29 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0015_remove_hotelimages_hotel_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
