# Generated by Django 4.2.14 on 2024-10-02 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0017_remove_hotelimages_hotel_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='hotel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bookingapp.hotel'),
        ),
    ]
