# Generated by Django 4.2.14 on 2024-10-02 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0018_remove_comment_hotelroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='hotelroom',
        ),
    ]
