# Generated by Django 4.2.14 on 2024-10-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0019_remove_comment_hotelroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
    ]
