# Generated by Django 4.2.14 on 2024-10-06 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0022_remove_hotelimages_hotel_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherrom',
            name='hotel_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookingapp.hotel'),
        ),
    ]
