# Generated by Django 4.2.14 on 2024-10-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0024_remove_hotelimages_hotel_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='is_checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
