# Generated by Django 4.2.14 on 2024-10-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0026_remove_hotelimages_hotel_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelrom',
            name='total_rooms',
            field=models.IntegerField(default=0),
        ),
    ]
