# Generated by Django 4.2.14 on 2024-10-11 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0027_remove_hotelimages_hotel_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucherpromotions',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='voucherpromotions',
            name='voucher',
        ),
        migrations.DeleteModel(
            name='Promotions',
        ),
        migrations.DeleteModel(
            name='VoucherPromotions',
        ),
    ]
